# Generated by Django 4.0.2 on 2022-03-18 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appnomina', '0003_alter_cargo_options_alter_cargo_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['id'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['id'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
