# Generated by Django 4.0.2 on 2022-03-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnomina', '0006_alter_departamento_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
