# Generated by Django 4.0.2 on 2022-03-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnomina', '0008_empleado_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
