# Generated by Django 4.0.2 on 2022-03-25 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appnomina', '0009_alter_empleado_cedula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['id'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
